% DeepSSIM Metric -- Matlab version
% Copyright(c) 2025 Keke Zhang, Weiling Chen, Tiesong Zhao and Zhou Wang.
% All Rights Reserved.
% Please refer to/cite the following paper: "Structural Similarity in Deep ...
% Features: Unified Image Quality Assessment Robust to Geometrically Disparate Reference" 
clear
clc

net_params = load('params_vgg16.mat');% "params_vgg16.mat" is the original pre-trained VGG16 weights.
load('vgg_mean.mat')
vggmean = vgg_mean;
load('vgg_std.mat')
vggstd = vgg_std;
use_gpu = 1;

ref_im = imread('butterfly.png');
dis_im = imread('butterfly_shif_0.50.png');

%% With Saliency Calibration 
% The saliency maps are generated by GBVS algorithms.
%% NOTE: If your application is not intended for image retargeting quality assessment...
% or other clarity lossless quality assessment tasks, we recommend using the version...
% labeled "Without Saliency Calibration" below, which offers a simpler computation...
% while delivering comparable performance.
sal_ref_im = imread('./saliency_maps/butterfly.png');
sal_dis_im = imread('./saliency_maps/butterfly_shif_0.50.png');

deepssim_score_withSC = DeepSSIM_wSC(ref_im,sal_ref_im,dis_im,sal_dis_im,net_params,use_gpu,vggmean,vggstd);

%% Without Saliency Calibration 
deepssim_score_withoutSC = DeepSSIM_woSC(ref_im,dis_im,net_params,use_gpu,vggmean,vggstd);